/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// ============================================
// PUSH EVENT: Handle incoming push notifications
// ============================================
self.addEventListener('push', (event) => {
  if (!event.data) {
    return;
  }

  try {
    const data = event.data.json();
    
    const options: NotificationOptions = {
      body: data.body || '',
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      tag: data.tag || 'default',
      data: {
        url: data.url || '/',
      },
      requireInteraction: false,
    };

    event.waitUntil(
      self.registration.showNotification(data.title || 'auto-m8', options)
    );
  } catch (error) {
    console.error('Error showing notification:', error);
  }
});

// ============================================
// NOTIFICATION CLICK: Handle notification clicks
// ============================================
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const url = event.notification.data?.url || '/';

  event.waitUntil(
    // Check if a window is already open
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Try to find an existing window and focus it
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          // Navigate to the URL
          if ('navigate' in client) {
            return (client as WindowClient).navigate(url);
          }
          return client;
        }
      }
      // No existing window, open a new one
      return self.clients.openWindow(url);
    })
  );
});

// ============================================
// ACTIVATE: Claim clients immediately
// ============================================
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
